export const STATUS = {
  CREATED: "CREATED",
  ASSIGNED: "ASSIGNED",
  RESOLVED: "RESOLVED",
  CLOSED: "CLOSED",
};

export const PERMISSION = {
  CreateAttachment: "canCreateAttachment",
  ReadAttachment: "canReadAttachment",
  UpdateAttachment: "canUpdateAttachment",
  DeleteAttachment: "canDeleteAttachment",
  CreateComment: "canCreateComment",
  ReadComment: "canReadComment",
  UpdateComment: "canUpdateComment",
  DeleteComment: "canDeleteComment",
  CreateIssue: "canCreateIssue",
  ReadIssue: "canReadIssue",
  AssignIssue: "canAssignIssue",
  ResolveIssue: "canResolveIssue",
  CloseIssue: "canCloseIssue",
  UpdateIssue: "canUpdateIssue",
  DeleteIssue: "canDeleteIssue",
  CreatePermission: "canCreatePermission",
  ReadPermission: "canReadPermission",
  UpdatePermission: "canUpdatePermission",
  DeletePermission: "canDeletePermission",
  CreateRole: "canCreateRole",
  ReadRole: "canReadRole",
  UpdateRole: "canUpdateRole",
  DeleteRole: "canDeleteRole",
  CreateTag: "canCreateTag",
  ReadTag: "canReadTag",
  UpdateTag: "canUpdateTag",
  DeleteTag: "canDeleteTag",
  CreateType: "canCreateType",
  ReadType: "canReadType",
  UpdateType: "canUpdateType",
  DeleteType: "canDeleteType",
  CreateUser: "canCreateUser",
  ReadUser: "canReadUser",
  UpdateUser: "canUpdateUser",
  DeleteUser: "canDeleteUser",
  ReadLog: "canReadLog",
  ReadDashboard: "canReadDashboard",
};
